export {default as Chat} from './Chat'
export {default as Home} from './Home'
export {default as Likes} from './Likes'
export {default as Notifications} from './Notifications'
export {default as Config} from './Config'